spring:
  application:
    name: raising-stocks

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML